version: "2"

services:
  app:
    build: .
    privileged: true
    working_dir: /app
    volumes:
      - ./config:/app/config
      - ./output:/app/output
      #- /run/udev:/run/udev:ro
      #- /etc/localtime:/etc/localtime:ro
    environment:
      - DOCKER_INFLUXDB_ORG=${DB_ORG}
      - DOCKER_INFLUXDB_BUCKET=${DB_BUCKET}
      - DOCKER_CURRENT_INFLUXDB_TOKEN=${DB_ADMIN_INITIAL_TOKEN}
