[mqtt]
url = "mqtt.local.docker" #129.169.48.174" "mqtt.local.docker"
port = 1883
topic_in = "AAS/send/in"
topic_out = "AAS/send/in"

[input.scanner]
serial = "0581_011c"
connection_point = ["0", "6", "0"]
