
[influx_info]
url = "http://129.169.48.175:8086"
org = "Design-studio"
token = "design-studio-lab"
frequency_record_seconds = 2

[frepple_info]
URL = "http://129.169.48.175:9000"
password = "admin"
user = "admin"

[Factory]
idShort = "Design_Studio_Facotry"
name = "Design Studio Facotry"                                       #"3D Printing"
machine = ["Laser_Cutter"]
frequencyUpdate = 1
fileType = "AAS"
first_check = 6500                                                   #hours
address = "Design Studio, Insitute for manufacturing, Cambridge, UK"
email = "sjb351@cam.ac.uk"
process = ["Cutting Lids Out"]
Make_AAS_from = "Data"
template_name = "Submodels_SR3.json"


[energy_use]
idShort = "energy_use"
name = "energy use"
frequency = "per product"       # per product, per order, per second
units = "kWh"                   #Units of the data, no impact on colelction
method = "tracking"             # data collected using signal peaks (signals) or tracking system (tracking), MES or <sensor>-MES combination
machine_list = ["Laser_Cutter"]


[material_use]
idShort = "material_use"
name = "material use"
frequency = "per product" # per product, per order, per second
units = "kg"              #Units of the data, no impact on colelction
method = "MES"            # data collected using signal peaks (signals) or tracking system (tracking), MES or <sensor>-MES combination

[material_type]
idShort = "material_type"
name = "material type"
frequency = "per order"   # per product, per order, per second
units = "kg"              #Units of the data, no impact on colelction
method = "MES"            # data collected using signal peaks (signals) or tracking system (tracking), MES or <sensor>-MES combination

[order_time_taken]
idShort = "order_time_taken"
name = "order time taken"
frequency = "per order"      # per product, per order, per second
method = "tracking"          # data collected using signal peaks (signals) or tracking system (tracking), MES or <sensor>-MES combination
machine = ["Laser_Cutter"]
start_location = "Job Start"
end_location = "Job End"
# [assembly_method]
# name = "assembly method"
# frequency= "per order" # per product, per order, per second
# units= "kg" #Units of the data, no impact on colelction
# method= "MES" # data collected using signal peaks (signals) or tracking system (tracking), MES or <sensor>-MES combination
# add_to_AAS = 1
