# config file for 3D printing lab
[Factory]
name = "Design_Studio"
sending_method = "Both"  # "Printing" or "MQTT" or "Store" or Both to show Both
reciving_method = "Both" # the method used to recieve (same as above)
# sending method = None means the AASX will be created
file_directory_out = "AAS_data/order/"

# 3D Printing: 129.169.48.173
# Robot Lab: 129.169.48.176
# Manual Assembly: 129.169.48.174
# Design Studio: 129.169.48.175

[external_layer.mqtt]
# external reciving partner
broker = "129.169.48.174" #"mqtt.docker.local"
port = 1883
base_topic_template = ""
topic = "AAS/send/in/"

reconnect.initial = 5 # seconds
reconnect.backoff = 2 # multiplier
reconnect.limit = 60  # seconds

[input.scanner]
serial = "0581_011c"
connection_point = ["0", "1", "1.0"]

[internal_layer.mqtt]
# internal sending to printer 
broker = "129.169.48.175" #"mqtt.docker.local"
port = 1883
base_topic_template = ""
topic = "AAS/print/"

reconnect.initial = 5 # seconds
reconnect.backoff = 2 # multiplier
reconnect.limit = 60  # seconds
